#ifndef ENUMTOKEN_H
#define ENUMTOKEN_H

namespace enumeradores
{

enum EnumToken
{
    VARIAVEL,
    PALAVRA_RESERVADA,
    OPERADOR_ATRIBUICAO,
    DELIMITADOR,
    OPERADOR_SEPARADOR,
    ID,
    FINAL_DE_LINHA,
    NUMERO,
    OPERADOR_LOGICO_SE,
    OPERADOR_LOGICO_ENTAO,
    OPERADOR_LOGICO_SENAO,
    OPERADOR_RELACIONAL_MAIOR,
    OPERADOR_RELACIONAL_MENOR,
    OPERADOR_RELACIONAL_MAIOR_IGUAL,
    OPERADOR_RELACIONAL_MENOR_IGUAL,
    OPERADOR_RELACIONAL_DIFERENTE,
    OPERADOR_ARITMETICO_SOMA,
    OPERADOR_ARITMETICO_SUBTRACAO,
    OPERADOR_ARITMETICO_MULTIPLICACAO,
    OPERADOR_ARITMETICO_DIVISAO,
    LEIA,
    ESCREVA,
    ABRE,
    FECHA,
    NOME_VARIAVEL
};

}

#endif // ENUMTOKEN_H
